# prefix of stack name
service: checkit-serverless-spike

# choose files in the package pushed to cloud
package:
  # package each function individually
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - resource-stack/**
    - .vscode/**
    - test-data/**

# serverless plugins
plugins:
  - serverless-iam-roles-per-function

# cloud service provider configuration
provider:
  name: aws
  timeout: 30
  memorySize: 512
  region: 'eu-west-1'
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'serverless'}
  runtime: nodejs8.10
  deploymentBucket:
    name: ${self:service}-deployment
  # apiGateway:
  #   apiKeySourceType: HEADER
  # apiKeys:
  #   - ${self:provider.stage}-myAPIKEY

# project customised settings
custom:
  functionPrefix: ${self:service}
  resourceStack: ${self:service}-resources-${self:provider.stage}

# lamdba configurations
functions:
  customerTemplate:
    handler: build/customerTemplate.create
    name: ${self:custom.functionPrefix}-customerTemplate
    events:
      - sqs:
        arn:
          Fn::GetAtt:
            - CustomerTemplateQueue
            - Arn
    package:
      include:
        - 'build/**'
        - '!*.*'
        - '!src/**'

resources:
  Resources:
    CustomerTemplateQueue:
      Type: AWS::SQS::Queue
      DeletionPolicy: Delete
      Properties:
        QueueName: "checkit-customer-template-test"
        MessageRetentionPeriod: 1209600
        VisibilityTimeout: 60

    CustomerTemplateSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: cusCreate,
        TopicName: "checkit-customer-template-test"
        Subscription:
          -
            Endpoint:
              Fn::GetAtt:
                - CustomerTemplateQueue
                - "Arn"
            Protocol: "sqs"